export { default as Navbar} from './Navbar'
export { default as Home} from './Home'
export { default as Cryptocurrencies} from './Cryptocurrencies'
export { default as CryptoDetail} from './CryptoDetail'
export { default as News} from './News'
export { default as Exchanges} from './Exchanges'
export { default as Loader} from './Loader'
export { default as Chartt} from './Chartt'